### ISSUE TITLE
The docker image outdated on the Docker Hub

### ISSUE THREAD

**Issue by dparalen** [rohanpm/docker-fedora-vagrant#1]
Hi @rohanpm, 

We've been using your Fedora Vagrant Docker image for [Pulp/devel](https://github.com/pulp/devel/) and we like it, it's just the last build was made for F26 which is now almost 3 versions outdated and we ran into an RPM [dependency issue](https://github.com/pulp/devel/issues/188) deploying Pulp. Do you plan on pushing up a newer build?

Thanks!
milan

**Comment by rohanpm** [comment]
@dparalen sure, thanks for letting me know.  You can now find also 27, 28 and 29 in https://hub.docker.com/r/rohanpm/fedora-vagrant/tags/ .  I'd also be interested to look into a way to do this automatically whenever there's new versions; filed https://github.com/rohanpm/docker-fedora-vagrant/issues/2.

Note: I don't have any kind of test procedure for those images, so all I can say right now is that they exist ... no idea yet if they're working properly.
